### ISSUE TITLE
Error: Expected "0.18.20" but got "0.19.12"

### ISSUE THREAD

**Issue by vporton** [kristoferlund/passport_score_issuer#1]
I want to try your package to see what it does (by the way, what does it do?), but get an error that I don't understand:
```
$ npm i
npm ERR! code 1
npm ERR! path /home/porton/t/passport-score-issuer/node_modules/esbuild
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! /home/porton/t/passport-score-issuer/node_modules/esbuild/install.js:132
npm ERR!     throw new Error(`Expected ${JSON.stringify(versionFromPackageJSON)} but got ${JSON.stringify(stdout)}`);
npm ERR!           ^
npm ERR! 
npm ERR! Error: Expected "0.18.20" but got "0.19.12"
npm ERR!     at validateBinaryVersion (/home/porton/t/passport-score-issuer/node_modules/esbuild/install.js:132:11)
npm ERR!     at /home/porton/t/passport-score-issuer/node_modules/esbuild/install.js:285:5
npm ERR! 
npm ERR! Node.js v21.5.0

npm ERR! A complete log of this run can be found in: /home/porton/.npm/_logs/2024-03-20T16_28_29_629Z-debug-0.log
```

Note that I did install `esbuild` 0.18.20 globally but this didn't eliminate the error.

**Comment by kristoferlund** [comment]
Hey @vporton! I did not see this issue until now. A lot has happened in the repo since March. If you will, please see if you get the same error.
